df<-openxlsx::read.xlsx("Table S1.xlsx")
df<-as_tibble(df)
df$Gender<-factor(df$Gender,levels = c("Male","Female"))
df$Age<-factor(df$Age,levels = c("<=65",">65"))
df$MIBC<-factor(df$MIBC,levels = c("NMIBC","MIBC"))
df$Grade<-factor(df$Grade,levels = c("Low","High"))
df$ecDNA.status<-factor(df$ecDNA.status,levels = c("Negative","Positive"))
df$EPM<-factor(df$EPM,levels = c("Low","High"))
library(survival)
fit <- coxph(Surv(OS, Survival)~Gender+Age+MIBC+Grade+ecDNA.status+EPM, data=df)
summary(fit)
fit <- coxph(Surv(PFS, Progression)~Gender+Age+MIBC+Grade+ecDNA.status+EPM, data=df)
summary(fit)
